version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands: 
      - npm i -g typescript
      - npm i
  
  build: 
    commands:
      - tsc

artifacts:
  files:
    - package.json
    - package-lock.json
    - 'dist/**/*'
    - '.platform/**/*'      # AWS EB config files
    - '.ebextensions/**/*' # AWS EB config files
  discard-paths: no