version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm uninstall typescript
      - npm install -g typescript
      - npm install
  
  build: 
    commands:
      - npm run build

artifacts:
  files:
    - package.json
    - tsconfig.json
    - 'dist/**/*'
    - '.platform/**/*'      # AWS EB config files
    - '.ebextensions/**/*' # AWS EB config files
  discard-paths: no